export interface Airport {
  code: string;
  name: string;
  city: string;
  country: string;
  countryCode: string;
}

export const AIRPORTS: Airport[] = [
  // ── United States ──────────────────────────────────────────
  { code: "LAX", name: "Los Angeles International", city: "Los Angeles", country: "United States", countryCode: "US" },
  { code: "SFO", name: "San Francisco International", city: "San Francisco", country: "United States", countryCode: "US" },
  { code: "JFK", name: "John F. Kennedy International", city: "New York", country: "United States", countryCode: "US" },
  { code: "EWR", name: "Newark Liberty International", city: "New York", country: "United States", countryCode: "US" },
  { code: "LGA", name: "LaGuardia Airport", city: "New York", country: "United States", countryCode: "US" },
  { code: "ORD", name: "O'Hare International", city: "Chicago", country: "United States", countryCode: "US" },
  { code: "MDW", name: "Midway International", city: "Chicago", country: "United States", countryCode: "US" },
  { code: "MIA", name: "Miami International", city: "Miami", country: "United States", countryCode: "US" },
  { code: "FLL", name: "Fort Lauderdale-Hollywood International", city: "Fort Lauderdale", country: "United States", countryCode: "US" },
  { code: "SEA", name: "Seattle-Tacoma International", city: "Seattle", country: "United States", countryCode: "US" },
  { code: "DFW", name: "Dallas/Fort Worth International", city: "Dallas", country: "United States", countryCode: "US" },
  { code: "ATL", name: "Hartsfield-Jackson Atlanta International", city: "Atlanta", country: "United States", countryCode: "US" },
  { code: "BOS", name: "Logan International", city: "Boston", country: "United States", countryCode: "US" },
  { code: "DEN", name: "Denver International", city: "Denver", country: "United States", countryCode: "US" },
  { code: "LAS", name: "Harry Reid International", city: "Las Vegas", country: "United States", countryCode: "US" },
  { code: "PHX", name: "Phoenix Sky Harbor International", city: "Phoenix", country: "United States", countryCode: "US" },
  { code: "MSP", name: "Minneapolis-Saint Paul International", city: "Minneapolis", country: "United States", countryCode: "US" },
  { code: "DTW", name: "Detroit Metropolitan Wayne County", city: "Detroit", country: "United States", countryCode: "US" },
  { code: "IAH", name: "George Bush Intercontinental", city: "Houston", country: "United States", countryCode: "US" },
  { code: "HOU", name: "William P. Hobby Airport", city: "Houston", country: "United States", countryCode: "US" },
  { code: "SAN", name: "San Diego International", city: "San Diego", country: "United States", countryCode: "US" },
  { code: "PDX", name: "Portland International", city: "Portland", country: "United States", countryCode: "US" },
  { code: "AUS", name: "Austin-Bergstrom International", city: "Austin", country: "United States", countryCode: "US" },
  { code: "CLT", name: "Charlotte Douglas International", city: "Charlotte", country: "United States", countryCode: "US" },
  { code: "MCO", name: "Orlando International", city: "Orlando", country: "United States", countryCode: "US" },
  { code: "HNL", name: "Daniel K. Inouye International", city: "Honolulu", country: "United States", countryCode: "US" },
  { code: "ANC", name: "Ted Stevens Anchorage International", city: "Anchorage", country: "United States", countryCode: "US" },
  { code: "SLC", name: "Salt Lake City International", city: "Salt Lake City", country: "United States", countryCode: "US" },
  { code: "PHL", name: "Philadelphia International", city: "Philadelphia", country: "United States", countryCode: "US" },
  { code: "DCA", name: "Ronald Reagan Washington National", city: "Washington D.C.", country: "United States", countryCode: "US" },
  { code: "IAD", name: "Washington Dulles International", city: "Washington D.C.", country: "United States", countryCode: "US" },
  { code: "BWI", name: "Baltimore/Washington International", city: "Baltimore", country: "United States", countryCode: "US" },
  { code: "PSP", name: "Palm Springs International", city: "Palm Springs", country: "United States", countryCode: "US" },
  // ── Canada ─────────────────────────────────────────────────
  { code: "YYZ", name: "Toronto Pearson International", city: "Toronto", country: "Canada", countryCode: "CA" },
  { code: "YVR", name: "Vancouver International", city: "Vancouver", country: "Canada", countryCode: "CA" },
  { code: "YUL", name: "Montréal-Trudeau International", city: "Montreal", country: "Canada", countryCode: "CA" },
  { code: "YYC", name: "Calgary International", city: "Calgary", country: "Canada", countryCode: "CA" },
  { code: "YOW", name: "Ottawa Macdonald-Cartier International", city: "Ottawa", country: "Canada", countryCode: "CA" },
  { code: "YEG", name: "Edmonton International", city: "Edmonton", country: "Canada", countryCode: "CA" },
  // ── Mexico ─────────────────────────────────────────────────
  { code: "MEX", name: "Benito Juárez International", city: "Mexico City", country: "Mexico", countryCode: "MX" },
  { code: "GDL", name: "Don Miguel Hidalgo International", city: "Guadalajara", country: "Mexico", countryCode: "MX" },
  { code: "CUN", name: "Cancún International", city: "Cancún", country: "Mexico", countryCode: "MX" },
  { code: "MTY", name: "General Mariano Escobedo International", city: "Monterrey", country: "Mexico", countryCode: "MX" },
  { code: "SJD", name: "Los Cabos International", city: "Los Cabos", country: "Mexico", countryCode: "MX" },
  // ── Caribbean & Central America ────────────────────────────
  { code: "SJU", name: "Luis Muñoz Marín International", city: "San Juan", country: "Puerto Rico", countryCode: "PR" },
  { code: "PTY", name: "Tocumen International", city: "Panama City", country: "Panama", countryCode: "PA" },
  { code: "SJO", name: "Juan Santamaría International", city: "San José", country: "Costa Rica", countryCode: "CR" },
  { code: "HAV", name: "José Martí International", city: "Havana", country: "Cuba", countryCode: "CU" },
  { code: "SDQ", name: "Las Américas International", city: "Santo Domingo", country: "Dominican Republic", countryCode: "DO" },
  // ── South America ──────────────────────────────────────────
  { code: "GRU", name: "São Paulo-Guarulhos International", city: "São Paulo", country: "Brazil", countryCode: "BR" },
  { code: "GIG", name: "Galeão International", city: "Rio de Janeiro", country: "Brazil", countryCode: "BR" },
  { code: "BSB", name: "Presidente Juscelino Kubitschek International", city: "Brasília", country: "Brazil", countryCode: "BR" },
  { code: "EZE", name: "Ministro Pistarini International", city: "Buenos Aires", country: "Argentina", countryCode: "AR" },
  { code: "SCL", name: "Arturo Merino Benítez International", city: "Santiago", country: "Chile", countryCode: "CL" },
  { code: "BOG", name: "El Dorado International", city: "Bogotá", country: "Colombia", countryCode: "CO" },
  { code: "MDE", name: "José María Córdova International", city: "Medellín", country: "Colombia", countryCode: "CO" },
  { code: "LIM", name: "Jorge Chávez International", city: "Lima", country: "Peru", countryCode: "PE" },
  { code: "CUZ", name: "Alejandro Velasco Astete International", city: "Cusco", country: "Peru", countryCode: "PE" },
  { code: "UIO", name: "Mariscal Sucre International", city: "Quito", country: "Ecuador", countryCode: "EC" },
  { code: "GYE", name: "José Joaquín de Olmedo International", city: "Guayaquil", country: "Ecuador", countryCode: "EC" },
  { code: "CCS", name: "Simón Bolívar International", city: "Caracas", country: "Venezuela", countryCode: "VE" },
  { code: "MVD", name: "Carrasco International", city: "Montevideo", country: "Uruguay", countryCode: "UY" },
  { code: "ASU", name: "Silvio Pettirossi International", city: "Asunción", country: "Paraguay", countryCode: "PY" },
  { code: "LPB", name: "El Alto International", city: "La Paz", country: "Bolivia", countryCode: "BO" },
  // ── United Kingdom ─────────────────────────────────────────
  { code: "LHR", name: "Heathrow Airport", city: "London", country: "United Kingdom", countryCode: "GB" },
  { code: "LGW", name: "Gatwick Airport", city: "London", country: "United Kingdom", countryCode: "GB" },
  { code: "STN", name: "Stansted Airport", city: "London", country: "United Kingdom", countryCode: "GB" },
  { code: "LCY", name: "London City Airport", city: "London", country: "United Kingdom", countryCode: "GB" },
  { code: "MAN", name: "Manchester Airport", city: "Manchester", country: "United Kingdom", countryCode: "GB" },
  { code: "EDI", name: "Edinburgh Airport", city: "Edinburgh", country: "United Kingdom", countryCode: "GB" },
  { code: "GLA", name: "Glasgow Airport", city: "Glasgow", country: "United Kingdom", countryCode: "GB" },
  { code: "BHX", name: "Birmingham Airport", city: "Birmingham", country: "United Kingdom", countryCode: "GB" },
  { code: "BRS", name: "Bristol Airport", city: "Bristol", country: "United Kingdom", countryCode: "GB" },
  // ── France ─────────────────────────────────────────────────
  { code: "CDG", name: "Charles de Gaulle Airport", city: "Paris", country: "France", countryCode: "FR" },
  { code: "ORY", name: "Paris-Orly Airport", city: "Paris", country: "France", countryCode: "FR" },
  { code: "NCE", name: "Nice Côte d'Azur Airport", city: "Nice", country: "France", countryCode: "FR" },
  { code: "LYS", name: "Lyon-Saint Exupéry Airport", city: "Lyon", country: "France", countryCode: "FR" },
  { code: "MRS", name: "Marseille Provence Airport", city: "Marseille", country: "France", countryCode: "FR" },
  { code: "BOD", name: "Bordeaux-Mérignac Airport", city: "Bordeaux", country: "France", countryCode: "FR" },
  { code: "TLS", name: "Toulouse-Blagnac Airport", city: "Toulouse", country: "France", countryCode: "FR" },
  // ── Germany ────────────────────────────────────────────────
  { code: "FRA", name: "Frankfurt Airport", city: "Frankfurt", country: "Germany", countryCode: "DE" },
  { code: "MUC", name: "Munich Airport", city: "Munich", country: "Germany", countryCode: "DE" },
  { code: "BER", name: "Berlin Brandenburg Airport", city: "Berlin", country: "Germany", countryCode: "DE" },
  { code: "DUS", name: "Düsseldorf Airport", city: "Düsseldorf", country: "Germany", countryCode: "DE" },
  { code: "HAM", name: "Hamburg Airport", city: "Hamburg", country: "Germany", countryCode: "DE" },
  { code: "STR", name: "Stuttgart Airport", city: "Stuttgart", country: "Germany", countryCode: "DE" },
  { code: "CGN", name: "Cologne Bonn Airport", city: "Cologne", country: "Germany", countryCode: "DE" },
  // ── Spain ──────────────────────────────────────────────────
  { code: "MAD", name: "Adolfo Suárez Madrid-Barajas Airport", city: "Madrid", country: "Spain", countryCode: "ES" },
  { code: "BCN", name: "Barcelona-El Prat Airport", city: "Barcelona", country: "Spain", countryCode: "ES" },
  { code: "AGP", name: "Málaga-Costa del Sol Airport", city: "Málaga", country: "Spain", countryCode: "ES" },
  { code: "VLC", name: "Valencia Airport", city: "Valencia", country: "Spain", countryCode: "ES" },
  { code: "PMI", name: "Palma de Mallorca Airport", city: "Palma de Mallorca", country: "Spain", countryCode: "ES" },
  { code: "SVQ", name: "Seville Airport", city: "Seville", country: "Spain", countryCode: "ES" },
  { code: "TFS", name: "Tenerife South Airport", city: "Tenerife", country: "Spain", countryCode: "ES" },
  { code: "LPA", name: "Gran Canaria Airport", city: "Las Palmas", country: "Spain", countryCode: "ES" },
  // ── Italy ──────────────────────────────────────────────────
  { code: "FCO", name: "Leonardo da Vinci International", city: "Rome", country: "Italy", countryCode: "IT" },
  { code: "MXP", name: "Milan Malpensa Airport", city: "Milan", country: "Italy", countryCode: "IT" },
  { code: "LIN", name: "Milan Linate Airport", city: "Milan", country: "Italy", countryCode: "IT" },
  { code: "VCE", name: "Venice Marco Polo Airport", city: "Venice", country: "Italy", countryCode: "IT" },
  { code: "NAP", name: "Naples International Airport", city: "Naples", country: "Italy", countryCode: "IT" },
  { code: "BGY", name: "Milan Bergamo Airport", city: "Bergamo", country: "Italy", countryCode: "IT" },
  { code: "PMO", name: "Palermo Airport", city: "Palermo", country: "Italy", countryCode: "IT" },
  { code: "CTA", name: "Catania-Fontanarossa Airport", city: "Catania", country: "Italy", countryCode: "IT" },
  { code: "FLR", name: "Florence Airport", city: "Florence", country: "Italy", countryCode: "IT" },
  // ── Netherlands, Belgium, Switzerland, Austria ─────────────
  { code: "AMS", name: "Amsterdam Airport Schiphol", city: "Amsterdam", country: "Netherlands", countryCode: "NL" },
  { code: "BRU", name: "Brussels Airport", city: "Brussels", country: "Belgium", countryCode: "BE" },
  { code: "ZRH", name: "Zurich Airport", city: "Zurich", country: "Switzerland", countryCode: "CH" },
  { code: "GVA", name: "Geneva Airport", city: "Geneva", country: "Switzerland", countryCode: "CH" },
  { code: "VIE", name: "Vienna International Airport", city: "Vienna", country: "Austria", countryCode: "AT" },
  { code: "SZG", name: "Salzburg Airport", city: "Salzburg", country: "Austria", countryCode: "AT" },
  // ── Portugal ───────────────────────────────────────────────
  { code: "LIS", name: "Humberto Delgado Airport", city: "Lisbon", country: "Portugal", countryCode: "PT" },
  { code: "OPO", name: "Francisco de Sá Carneiro Airport", city: "Porto", country: "Portugal", countryCode: "PT" },
  { code: "FAO", name: "Faro Airport", city: "Faro", country: "Portugal", countryCode: "PT" },
  // ── Scandinavia & Iceland ──────────────────────────────────
  { code: "ARN", name: "Stockholm Arlanda Airport", city: "Stockholm", country: "Sweden", countryCode: "SE" },
  { code: "GOT", name: "Gothenburg Landvetter Airport", city: "Gothenburg", country: "Sweden", countryCode: "SE" },
  { code: "CPH", name: "Copenhagen Airport", city: "Copenhagen", country: "Denmark", countryCode: "DK" },
  { code: "OSL", name: "Oslo Gardermoen Airport", city: "Oslo", country: "Norway", countryCode: "NO" },
  { code: "BGO", name: "Bergen Airport, Flesland", city: "Bergen", country: "Norway", countryCode: "NO" },
  { code: "HEL", name: "Helsinki-Vantaa Airport", city: "Helsinki", country: "Finland", countryCode: "FI" },
  { code: "KEF", name: "Keflavík International Airport", city: "Reykjavík", country: "Iceland", countryCode: "IS" },
  // ── Ireland & Greece ───────────────────────────────────────
  { code: "DUB", name: "Dublin Airport", city: "Dublin", country: "Ireland", countryCode: "IE" },
  { code: "ATH", name: "Athens Eleftherios Venizelos International", city: "Athens", country: "Greece", countryCode: "GR" },
  { code: "HER", name: "Heraklion International Airport", city: "Heraklion", country: "Greece", countryCode: "GR" },
  { code: "SKG", name: "Thessaloniki Macedonia International", city: "Thessaloniki", country: "Greece", countryCode: "GR" },
  { code: "CFU", name: "Corfu International Airport", city: "Corfu", country: "Greece", countryCode: "GR" },
  { code: "RHO", name: "Rhodes Diagoras Airport", city: "Rhodes", country: "Greece", countryCode: "GR" },
  { code: "JMK", name: "Mykonos Island National Airport", city: "Mykonos", country: "Greece", countryCode: "GR" },
  { code: "JTR", name: "Santorini (Thira) National Airport", city: "Santorini", country: "Greece", countryCode: "GR" },
  // ── Turkey ─────────────────────────────────────────────────
  { code: "IST", name: "Istanbul Airport", city: "Istanbul", country: "Turkey", countryCode: "TR" },
  { code: "SAW", name: "Istanbul Sabiha Gökçen International", city: "Istanbul", country: "Turkey", countryCode: "TR" },
  { code: "AYT", name: "Antalya Airport", city: "Antalya", country: "Turkey", countryCode: "TR" },
  { code: "ESB", name: "Esenboğa International Airport", city: "Ankara", country: "Turkey", countryCode: "TR" },
  { code: "ADB", name: "Adnan Menderes Airport", city: "Izmir", country: "Turkey", countryCode: "TR" },
  // ── Poland, Czech, Hungary ─────────────────────────────────
  { code: "WAW", name: "Warsaw Chopin Airport", city: "Warsaw", country: "Poland", countryCode: "PL" },
  { code: "KRK", name: "Kraków John Paul II International", city: "Kraków", country: "Poland", countryCode: "PL" },
  { code: "GDN", name: "Gdańsk Lech Wałęsa Airport", city: "Gdańsk", country: "Poland", countryCode: "PL" },
  { code: "PRG", name: "Václav Havel Airport Prague", city: "Prague", country: "Czech Republic", countryCode: "CZ" },
  { code: "BUD", name: "Budapest Ferenc Liszt International", city: "Budapest", country: "Hungary", countryCode: "HU" },
  // ── Balkans, Eastern Europe ────────────────────────────────
  { code: "BEG", name: "Belgrade Nikola Tesla Airport", city: "Belgrade", country: "Serbia", countryCode: "RS" },
  { code: "ZAG", name: "Zagreb Airport", city: "Zagreb", country: "Croatia", countryCode: "HR" },
  { code: "DBV", name: "Dubrovnik Airport", city: "Dubrovnik", country: "Croatia", countryCode: "HR" },
  { code: "SPU", name: "Split Airport", city: "Split", country: "Croatia", countryCode: "HR" },
  { code: "SOF", name: "Sofia Airport", city: "Sofia", country: "Bulgaria", countryCode: "BG" },
  { code: "OTP", name: "Henri Coandă International Airport", city: "Bucharest", country: "Romania", countryCode: "RO" },
  { code: "KBP", name: "Boryspil International Airport", city: "Kyiv", country: "Ukraine", countryCode: "UA" },
  { code: "SVO", name: "Sheremetyevo International Airport", city: "Moscow", country: "Russia", countryCode: "RU" },
  { code: "DME", name: "Domodedovo International Airport", city: "Moscow", country: "Russia", countryCode: "RU" },
  { code: "LED", name: "Pulkovo Airport", city: "Saint Petersburg", country: "Russia", countryCode: "RU" },
  // ── Middle East ────────────────────────────────────────────
  { code: "DXB", name: "Dubai International Airport", city: "Dubai", country: "United Arab Emirates", countryCode: "AE" },
  { code: "AUH", name: "Abu Dhabi International Airport", city: "Abu Dhabi", country: "United Arab Emirates", countryCode: "AE" },
  { code: "DOH", name: "Hamad International Airport", city: "Doha", country: "Qatar", countryCode: "QA" },
  { code: "RUH", name: "King Khalid International Airport", city: "Riyadh", country: "Saudi Arabia", countryCode: "SA" },
  { code: "JED", name: "King Abdulaziz International Airport", city: "Jeddah", country: "Saudi Arabia", countryCode: "SA" },
  { code: "MCT", name: "Muscat International Airport", city: "Muscat", country: "Oman", countryCode: "OM" },
  { code: "KWI", name: "Kuwait International Airport", city: "Kuwait City", country: "Kuwait", countryCode: "KW" },
  { code: "BAH", name: "Bahrain International Airport", city: "Manama", country: "Bahrain", countryCode: "BH" },
  { code: "TLV", name: "Ben Gurion International Airport", city: "Tel Aviv", country: "Israel", countryCode: "IL" },
  { code: "AMM", name: "Queen Alia International Airport", city: "Amman", country: "Jordan", countryCode: "JO" },
  { code: "BEY", name: "Rafic Hariri International Airport", city: "Beirut", country: "Lebanon", countryCode: "LB" },
  // ── Africa ─────────────────────────────────────────────────
  { code: "CAI", name: "Cairo International Airport", city: "Cairo", country: "Egypt", countryCode: "EG" },
  { code: "HRG", name: "Hurghada International Airport", city: "Hurghada", country: "Egypt", countryCode: "EG" },
  { code: "SSH", name: "Sharm el-Sheikh International", city: "Sharm el-Sheikh", country: "Egypt", countryCode: "EG" },
  { code: "CMN", name: "Mohammed V International Airport", city: "Casablanca", country: "Morocco", countryCode: "MA" },
  { code: "RAK", name: "Marrakesh Menara Airport", city: "Marrakesh", country: "Morocco", countryCode: "MA" },
  { code: "TUN", name: "Tunis-Carthage International Airport", city: "Tunis", country: "Tunisia", countryCode: "TN" },
  { code: "ALG", name: "Houari Boumediene Airport", city: "Algiers", country: "Algeria", countryCode: "DZ" },
  { code: "ADD", name: "Addis Ababa Bole International", city: "Addis Ababa", country: "Ethiopia", countryCode: "ET" },
  { code: "NBO", name: "Jomo Kenyatta International Airport", city: "Nairobi", country: "Kenya", countryCode: "KE" },
  { code: "DAR", name: "Julius Nyerere International Airport", city: "Dar es Salaam", country: "Tanzania", countryCode: "TZ" },
  { code: "ZNZ", name: "Abeid Amani Karume International", city: "Zanzibar", country: "Tanzania", countryCode: "TZ" },
  { code: "JNB", name: "O.R. Tambo International Airport", city: "Johannesburg", country: "South Africa", countryCode: "ZA" },
  { code: "CPT", name: "Cape Town International Airport", city: "Cape Town", country: "South Africa", countryCode: "ZA" },
  { code: "DUR", name: "King Shaka International Airport", city: "Durban", country: "South Africa", countryCode: "ZA" },
  { code: "LOS", name: "Murtala Muhammed International Airport", city: "Lagos", country: "Nigeria", countryCode: "NG" },
  { code: "ABV", name: "Nnamdi Azikiwe International Airport", city: "Abuja", country: "Nigeria", countryCode: "NG" },
  { code: "ACC", name: "Kotoka International Airport", city: "Accra", country: "Ghana", countryCode: "GH" },
  { code: "DKR", name: "Blaise Diagne International Airport", city: "Dakar", country: "Senegal", countryCode: "SN" },
  { code: "KGL", name: "Kigali International Airport", city: "Kigali", country: "Rwanda", countryCode: "RW" },
  { code: "MRU", name: "Sir Seewoosagur Ramgoolam International", city: "Port Louis", country: "Mauritius", countryCode: "MU" },
  // ── Japan ──────────────────────────────────────────────────
  { code: "HND", name: "Tokyo Haneda Airport", city: "Tokyo", country: "Japan", countryCode: "JP" },
  { code: "NRT", name: "Narita International Airport", city: "Tokyo", country: "Japan", countryCode: "JP" },
  { code: "KIX", name: "Kansai International Airport", city: "Osaka", country: "Japan", countryCode: "JP" },
  { code: "ITM", name: "Osaka Itami Airport", city: "Osaka", country: "Japan", countryCode: "JP" },
  { code: "NGO", name: "Chubu Centrair International", city: "Nagoya", country: "Japan", countryCode: "JP" },
  { code: "CTS", name: "New Chitose Airport", city: "Sapporo", country: "Japan", countryCode: "JP" },
  { code: "FUK", name: "Fukuoka Airport", city: "Fukuoka", country: "Japan", countryCode: "JP" },
  { code: "OKA", name: "Naha Airport", city: "Okinawa", country: "Japan", countryCode: "JP" },
  // ── South Korea ────────────────────────────────────────────
  { code: "ICN", name: "Incheon International Airport", city: "Seoul", country: "South Korea", countryCode: "KR" },
  { code: "GMP", name: "Gimpo International Airport", city: "Seoul", country: "South Korea", countryCode: "KR" },
  { code: "PUS", name: "Gimhae International Airport", city: "Busan", country: "South Korea", countryCode: "KR" },
  { code: "CJU", name: "Jeju International Airport", city: "Jeju", country: "South Korea", countryCode: "KR" },
  // ── China ──────────────────────────────────────────────────
  { code: "PEK", name: "Beijing Capital International Airport", city: "Beijing", country: "China", countryCode: "CN" },
  { code: "PKX", name: "Beijing Daxing International Airport", city: "Beijing", country: "China", countryCode: "CN" },
  { code: "PVG", name: "Shanghai Pudong International Airport", city: "Shanghai", country: "China", countryCode: "CN" },
  { code: "SHA", name: "Shanghai Hongqiao International Airport", city: "Shanghai", country: "China", countryCode: "CN" },
  { code: "CAN", name: "Guangzhou Baiyun International Airport", city: "Guangzhou", country: "China", countryCode: "CN" },
  { code: "SZX", name: "Shenzhen Bao'an International Airport", city: "Shenzhen", country: "China", countryCode: "CN" },
  { code: "CTU", name: "Chengdu Tianfu International Airport", city: "Chengdu", country: "China", countryCode: "CN" },
  { code: "KMG", name: "Kunming Changshui International Airport", city: "Kunming", country: "China", countryCode: "CN" },
  { code: "XIY", name: "Xi'an Xianyang International Airport", city: "Xi'an", country: "China", countryCode: "CN" },
  { code: "HGH", name: "Hangzhou Xiaoshan International Airport", city: "Hangzhou", country: "China", countryCode: "CN" },
  { code: "CKG", name: "Chongqing Jiangbei International Airport", city: "Chongqing", country: "China", countryCode: "CN" },
  { code: "URC", name: "Ürümqi Diwopu International Airport", city: "Ürümqi", country: "China", countryCode: "CN" },
  // ── Hong Kong & Taiwan ─────────────────────────────────────
  { code: "HKG", name: "Hong Kong International Airport", city: "Hong Kong", country: "Hong Kong", countryCode: "HK" },
  { code: "TPE", name: "Taiwan Taoyuan International Airport", city: "Taipei", country: "Taiwan", countryCode: "TW" },
  { code: "KHH", name: "Kaohsiung International Airport", city: "Kaohsiung", country: "Taiwan", countryCode: "TW" },
  // ── Southeast Asia ─────────────────────────────────────────
  { code: "SIN", name: "Singapore Changi Airport", city: "Singapore", country: "Singapore", countryCode: "SG" },
  { code: "KUL", name: "Kuala Lumpur International Airport", city: "Kuala Lumpur", country: "Malaysia", countryCode: "MY" },
  { code: "PEN", name: "Penang International Airport", city: "Penang", country: "Malaysia", countryCode: "MY" },
  { code: "BKI", name: "Kota Kinabalu International Airport", city: "Kota Kinabalu", country: "Malaysia", countryCode: "MY" },
  { code: "BKK", name: "Suvarnabhumi Airport", city: "Bangkok", country: "Thailand", countryCode: "TH" },
  { code: "DMK", name: "Don Mueang International Airport", city: "Bangkok", country: "Thailand", countryCode: "TH" },
  { code: "CNX", name: "Chiang Mai International Airport", city: "Chiang Mai", country: "Thailand", countryCode: "TH" },
  { code: "HKT", name: "Phuket International Airport", city: "Phuket", country: "Thailand", countryCode: "TH" },
  { code: "USM", name: "Samui Airport", city: "Koh Samui", country: "Thailand", countryCode: "TH" },
  { code: "CGK", name: "Soekarno-Hatta International Airport", city: "Jakarta", country: "Indonesia", countryCode: "ID" },
  { code: "DPS", name: "Ngurah Rai International Airport", city: "Bali", country: "Indonesia", countryCode: "ID" },
  { code: "SUB", name: "Juanda International Airport", city: "Surabaya", country: "Indonesia", countryCode: "ID" },
  { code: "MNL", name: "Ninoy Aquino International Airport", city: "Manila", country: "Philippines", countryCode: "PH" },
  { code: "CEB", name: "Mactan-Cebu International Airport", city: "Cebu", country: "Philippines", countryCode: "PH" },
  { code: "SGN", name: "Tan Son Nhat International Airport", city: "Ho Chi Minh City", country: "Vietnam", countryCode: "VN" },
  { code: "HAN", name: "Noi Bai International Airport", city: "Hanoi", country: "Vietnam", countryCode: "VN" },
  { code: "DAD", name: "Da Nang International Airport", city: "Da Nang", country: "Vietnam", countryCode: "VN" },
  { code: "PQC", name: "Phu Quoc International Airport", city: "Phú Quốc", country: "Vietnam", countryCode: "VN" },
  { code: "REP", name: "Siem Reap-Angkor International Airport", city: "Siem Reap", country: "Cambodia", countryCode: "KH" },
  { code: "PNH", name: "Phnom Penh International Airport", city: "Phnom Penh", country: "Cambodia", countryCode: "KH" },
  { code: "RGN", name: "Yangon International Airport", city: "Yangon", country: "Myanmar", countryCode: "MM" },
  // ── South Asia ─────────────────────────────────────────────
  { code: "DEL", name: "Indira Gandhi International Airport", city: "New Delhi", country: "India", countryCode: "IN" },
  { code: "BOM", name: "Chhatrapati Shivaji Maharaj International", city: "Mumbai", country: "India", countryCode: "IN" },
  { code: "MAA", name: "Chennai International Airport", city: "Chennai", country: "India", countryCode: "IN" },
  { code: "BLR", name: "Kempegowda International Airport", city: "Bangalore", country: "India", countryCode: "IN" },
  { code: "CCU", name: "Netaji Subhas Chandra Bose International", city: "Kolkata", country: "India", countryCode: "IN" },
  { code: "HYD", name: "Rajiv Gandhi International Airport", city: "Hyderabad", country: "India", countryCode: "IN" },
  { code: "GOI", name: "Goa International Airport", city: "Goa", country: "India", countryCode: "IN" },
  { code: "AMD", name: "Sardar Vallabhbhai Patel International", city: "Ahmedabad", country: "India", countryCode: "IN" },
  { code: "JAI", name: "Jaipur International Airport", city: "Jaipur", country: "India", countryCode: "IN" },
  { code: "CMB", name: "Bandaranaike International Airport", city: "Colombo", country: "Sri Lanka", countryCode: "LK" },
  { code: "KTM", name: "Tribhuvan International Airport", city: "Kathmandu", country: "Nepal", countryCode: "NP" },
  { code: "DAC", name: "Hazrat Shahjalal International Airport", city: "Dhaka", country: "Bangladesh", countryCode: "BD" },
  { code: "MLE", name: "Velana International Airport", city: "Malé", country: "Maldives", countryCode: "MV" },
  { code: "PBH", name: "Paro Airport", city: "Paro", country: "Bhutan", countryCode: "BT" },
  // ── Central Asia ───────────────────────────────────────────
  { code: "ALA", name: "Almaty International Airport", city: "Almaty", country: "Kazakhstan", countryCode: "KZ" },
  { code: "NQZ", name: "Nursultan Nazarbayev International", city: "Nur-Sultan", country: "Kazakhstan", countryCode: "KZ" },
  { code: "TAS", name: "Tashkent International Airport", city: "Tashkent", country: "Uzbekistan", countryCode: "UZ" },
  { code: "TBS", name: "Tbilisi International Airport", city: "Tbilisi", country: "Georgia", countryCode: "GE" },
  { code: "EVN", name: "Zvartnots International Airport", city: "Yerevan", country: "Armenia", countryCode: "AM" },
  { code: "GYD", name: "Heydar Aliyev International Airport", city: "Baku", country: "Azerbaijan", countryCode: "AZ" },
  // ── Oceania ────────────────────────────────────────────────
  { code: "SYD", name: "Sydney Kingsford Smith Airport", city: "Sydney", country: "Australia", countryCode: "AU" },
  { code: "MEL", name: "Melbourne Airport", city: "Melbourne", country: "Australia", countryCode: "AU" },
  { code: "BNE", name: "Brisbane Airport", city: "Brisbane", country: "Australia", countryCode: "AU" },
  { code: "PER", name: "Perth Airport", city: "Perth", country: "Australia", countryCode: "AU" },
  { code: "ADL", name: "Adelaide Airport", city: "Adelaide", country: "Australia", countryCode: "AU" },
  { code: "DRW", name: "Darwin International Airport", city: "Darwin", country: "Australia", countryCode: "AU" },
  { code: "CNS", name: "Cairns Airport", city: "Cairns", country: "Australia", countryCode: "AU" },
  { code: "AKL", name: "Auckland Airport", city: "Auckland", country: "New Zealand", countryCode: "NZ" },
  { code: "CHC", name: "Christchurch Airport", city: "Christchurch", country: "New Zealand", countryCode: "NZ" },
  { code: "WLG", name: "Wellington Airport", city: "Wellington", country: "New Zealand", countryCode: "NZ" },
  { code: "ZQN", name: "Queenstown Airport", city: "Queenstown", country: "New Zealand", countryCode: "NZ" },
  { code: "NAN", name: "Nadi International Airport", city: "Nadi", country: "Fiji", countryCode: "FJ" },
  { code: "PPT", name: "Faa'a International Airport", city: "Papeete", country: "French Polynesia", countryCode: "PF" },
];

export function searchAirports(query: string): Airport[] {
  if (!query || query.trim().length < 2) return [];
  const q = query.trim().toLowerCase();
  return AIRPORTS.filter(
    (a) =>
      a.code.toLowerCase().startsWith(q) ||
      a.city.toLowerCase().includes(q) ||
      a.country.toLowerCase().includes(q) ||
      a.name.toLowerCase().includes(q)
  ).slice(0, 6);
}
